version: '3'
services:
  service1:
    build: ./app/service1
    ports:
      - "5001:5001"

  service2:
    build: ./app/service2
    ports:
      - "5002:5002"

  nginx:
    image: nginx
    ports:
      - "3600:80"
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
      - service2
