version: '3'
services:
  service1:
    build: ./app/service1
    ports:
      - "5001:5001"
  service2:
    build: ./app/service2
    ports:
      - "5002:5002"
  nginx:
    image: nginx
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3600:80"
