name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/sree

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.LAPTOP_VSCODE_SSH_PRIVATE_KEY }}

      - name: Deploy to CentOS VM
        run: |
          ssh -o StrictHostKeyChecking=no vagrant@192.168.56.60 << 'EOF'
            cd /home/vagrant/DevOps-Local-Labs/vagrant-devops-project
            git pull origin main
            docker compose down
            docker compose up --build -d
          EOF
